### ISSUE TITLE
"ModuleNotFoundError: No module named 'quantumsim.circuit'"

### ISSUE THREAD

**Issue by vasudhapinkfairy** [quantumsim/qsoverlay#12]
While importing qsoverlay after importing quantumsim, it shows the error 
ModuleNotFoundError: No module named 'quantumsim.circuit'
I have installed quantumsim and qsoverlay in the same way that is given.

**Comment by obriente** [comment]
What branch of quantumsim are you using? This is currently under a lot of development so I think the advice on which branches to use might be wrong.

I suggest using the feature/full_iswap branch on both quantumsim and qsoverlay

**Comment by vasudhapinkfairy** [comment]
thanks !!

**Comment by slavoutich** [comment]
I had some problems with `feature/full_iswap`, but I assume PyPi version of quantumsim (which is `stable/v0.2` branch) should also work.
