### ISSUE TITLE
Introduction notebook outdated

### ISSUE THREAD

**Issue by BorisVarbanov** [quantumsim/qsoverlay#2]
In the Introduction notebook the Setup is treated as a subscriptable object (and instead the contained dictionaries are now simply class members), resulting in TypeError erros. This occurs on cell 3, where the dictionaries are accessed `(setup['qubit_dic'])` and in cells 4,10,12 where the setup is incorrectly unpacked (`**setup`). @obriente

**Comment by slavoutich** [comment]
Fixed already, I guess.
